export const CHANGE_CURRENT_SONG = "CHANGE_CURRENT_SONG";

export const CHANGE_SONG_LIST = "CHANGE_SONG_LIST";
export const CHANGE_CURRENT_SONG_INDEX = "CHANGE_CURRENT_SONG_INDEX";

export const CHANGE_SEQUENCE = "CHANGE_SEQUENCE";


export const CHANGE_LYRIC_List = "CHANGE_LYRIC_List";

export const CHANGE_CURRENT_LYRIC_INDEX = "CHANGE_CURRENT_LYRIC_INDEX";