export const CHANG_BANNER = "CHANG_BANNER";
export const CHANG_HOT_RECOMMEND = "CHANG_HOT_RECOMMENDR";
export const CHANG_NEW_SONG = "CHANG_NEW_SONG";
// export const CHANG_SONG_RANKING = "CHANG_SONG_RANKING";

export const CHANGG_SONG_RANKING_ACG = "CHANGG_SONG_RANKING_ACG";
export const CHANGG_SONG_RANKING_SOAR = "CHANGG_SONG_RANKING_SOAR";
export const CHANGG_SONG_RANKING_ELECTRONIC_MUSIC = "CHANGG_SONG_RANKING_ELECTRONIC_MUSIC";
export const CHANGG_SONG_RANKING_VIP = "CHANGG_SONG_RANKING_VIP";


export const CHANG_HOT_HOST = "CHANG_HOT_HOST";

